---
title: "sec-7-team-7"
subtitle: "STA 199 Project"
format: html
editor: visual
---

This research project investigated how heart disease presence and magnitude vary based on age, sex, cholesterol, blood sugar, and blood pressure as well as which of these variables is the best predictor of whether or not an individual will get heart disease. For analysis of the best predictors of heart disease, this project used data collected at the Hungarian Institute of Cardiology and Cleveland Clinic Foundation was used. This dataset consisted of 920 observations that each represent a case of heart disease with data for 16 variables, however, this analysis was centered around the variables *age, sex, num, trestbps, chol* and *fbs*. Through exploratory data analysis, it was concluded that heart disease rates are higher for men and people with fasting flood sugar above 150 mg/dl and rates tend to increase as age, cholesterol and blood pressure increase. Logistic regressions and AIC were utilized and it was determined that the best model was an additive of cholesterol and sex (AIC = 919.4695), with the second best model being an interactive of cholesterol and age (AIC = 926). From this analysis, it was determined that cholesterol and sex are the two best predictors of whether or not an individual will have heart disease.
